#!/usr/bin/python
def raise_exception():
    result = 5 + "i am a string, therefore i cannot be added onto 5, thus producing a \
        type error exception :)"
